#!/bin/bash
#
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=10
#SBATCH --time=120:00:00
#SBATCH --mem=62GB
#SBATCH --job-name=juicer
#SBATCH --output=slurm_%j.out
#SBATCH --mail-type=END
#SBATCH --mail-user=aa7013@nyu.edu

module purge
module load bwa/intel/0.7.17
module load jdk/11.0.9

##
# -D location of scripts directory
# -d working directory
# -p chrom.sizes file
# -z reference genome file
# -y restriction site file generated by generate_site_positions.py from Juicer. Note: you will have add your restriction sites to this file.
# -g genome ID

##
# Your directories should look like this
# Juicer
#   references
#   restriction_sites
#   references
#   working_directory
#       fastq

## 
# references contains reference genome and chrom.sizes files
# restriction_sites contains txt files generated by generate_site_positions.py
# working_directory contains run-juicer.sh script
# fastq contains fastq files in this format file_R1.fastq.gz 

## Steps
# use bwa index to generate index file 
# generate chrom.sizes file with the following code: samtools faidx genome.fa | cut -f1,2 > file.chrom.sizes
# add your genome to the juicer.sh file located in the scripts directory and give it a genome ID
# generate restriction site txt file by calling generate_site_positions.py with the run_RS.sh script. You will have to add your restrcition sites to the generate_site_positions.py script and give it an ID before running.
# run run_juicer.sh

/scratch/cgsb/ercan/Avrami/juicer/scripts/juicer.sh \
        -D /scratch/cgsb/ercan/Avrami/juicer \
        -t 10 \
        -d /scratch/cgsb/ercan/Avrami/juicer/Cre_PRJNA577507_wd \
        -p /scratch/cgsb/ercan/Avrami/juicer/references/GCF_010183535.1_CRPX506_genomic_chr-only.chrom.sizes \
        -z /scratch/cgsb/ercan/Avrami/juicer/references/GCF_010183535.1_CRPX506_genomic_chr-only.fna \
        -y /scratch/cgsb/ercan/Avrami/juicer/restriction_sites/Cre_GCF_010183535.1_CRPX506_DpnII.txt \
        -g PX506

echo done