---
title: "H4K20me1 stats"
author: "Avrami"
date: "2024-05-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load data
```{r}

H4K20me1_gene_body_N2 <- read.table("N2_H4K20me1_merged_gene_body.tsv", header = TRUE)

H4K20me1_gene_body_PS312 <- read.table("PS312_H4K20me1_merged_gene_body.tsv", header = TRUE)

H4K20me1_gene_body_CEW1 <- read.table("CEW1_H4K20me1_merged_gene_body.tsv", header = TRUE)

```

***C. elegans***
```{r}

## VARIABLES ##
chrI = "I"
chrII = "II"
chrIII = "III"
chrIV = "IV"
chrV = "V"
chrX = "X"
##

H4K20me1_gene_body_N2.I <- H4K20me1_gene_body_N2$zscore[H4K20me1_gene_body_N2$chromosome == chrI]
H4K20me1_gene_body_N2.II <- H4K20me1_gene_body_N2$zscore[H4K20me1_gene_body_N2$chromosome == chrII]
H4K20me1_gene_body_N2.III <- H4K20me1_gene_body_N2$zscore[H4K20me1_gene_body_N2$chromosome == chrIII]
H4K20me1_gene_body_N2.IV <- H4K20me1_gene_body_N2$zscore[H4K20me1_gene_body_N2$chromosome == chrIV]
H4K20me1_gene_body_N2.V <- H4K20me1_gene_body_N2$zscore[H4K20me1_gene_body_N2$chromosome == chrV]
H4K20me1_gene_body_N2.X <- H4K20me1_gene_body_N2$zscore[H4K20me1_gene_body_N2$chromosome == chrX]

# these are sanity checks. compare with your summary statistics
mean(H4K20me1_gene_body_N2.I, na.rm = TRUE)
mean(H4K20me1_gene_body_N2.II, na.rm = TRUE)
mean(H4K20me1_gene_body_N2.III, na.rm = TRUE)
mean(H4K20me1_gene_body_N2.IV, na.rm = TRUE)
mean(H4K20me1_gene_body_N2.V, na.rm = TRUE)
mean(H4K20me1_gene_body_N2.X, na.rm = TRUE)

length(H4K20me1_gene_body_N2.I)
length(H4K20me1_gene_body_N2.II)
length(H4K20me1_gene_body_N2.III)
length(H4K20me1_gene_body_N2.IV)
length(H4K20me1_gene_body_N2.V)
length(H4K20me1_gene_body_N2.X)

```

```{r}

## VARIABLES ##
autosomes <- c(chrI, chrII, chrIII, chrIV)
notI <- c(chrII, chrIII, chrIV, chrX)
notII <- c(chrI, chrIII, chrIV, chrX)
notIII <- c(chrI, chrII, chrIV, chrX)
notIV <- c(chrI, chrII, chrIII, chrX)
notV <- c(chrI, chrII, chrIII, chrIV, chrX)

# subset
H4K20me1_gene_body_N2.A <- H4K20me1_gene_body_N2$zscore[H4K20me1_gene_body_N2$chromosome %in% autosomes]
H4K20me1_gene_body_N2.notI <- H4K20me1_gene_body_N2$zscore[H4K20me1_gene_body_N2$chromosome %in% notI]
H4K20me1_gene_body_N2.notII <- H4K20me1_gene_body_N2$zscore[H4K20me1_gene_body_N2$chromosome %in% notII]
H4K20me1_gene_body_N2.notIII <- H4K20me1_gene_body_N2$zscore[H4K20me1_gene_body_N2$chromosome %in% notIII]
H4K20me1_gene_body_N2.notIV <- H4K20me1_gene_body_N2$zscore[H4K20me1_gene_body_N2$chromosome %in% notIV]
H4K20me1_gene_body_N2.notV <- H4K20me1_gene_body_N2$zscore[H4K20me1_gene_body_N2$chromosome %in% notV]

# sanity check
mean(H4K20me1_gene_body_N2.A, na.rm = TRUE)
mean(H4K20me1_gene_body_N2.notI, na.rm = TRUE)
mean(H4K20me1_gene_body_N2.notII, na.rm = TRUE)
mean(H4K20me1_gene_body_N2.notIII, na.rm = TRUE)
mean(H4K20me1_gene_body_N2.notIV, na.rm = TRUE)
mean(H4K20me1_gene_body_N2.notV, na.rm = TRUE)

length(H4K20me1_gene_body_N2.A)
length(H4K20me1_gene_body_N2.notI)
length(H4K20me1_gene_body_N2.notII)
length(H4K20me1_gene_body_N2.notIII)
length(H4K20me1_gene_body_N2.notIV)
length(H4K20me1_gene_body_N2.notV)

```

```{r}

wilcox.Xvs.N2 <- wilcox.test(H4K20me1_gene_body_N2.X, H4K20me1_gene_body_N2.A, alternative = "greater")
wilcox.Ivs.N2 <- wilcox.test(H4K20me1_gene_body_N2.I, H4K20me1_gene_body_N2.notI, alternative = "greater")
wilcox.IIvs.N2 <- wilcox.test(H4K20me1_gene_body_N2.II, H4K20me1_gene_body_N2.notII, alternative = "greater")
wilcox.IIIvs.N2 <- wilcox.test(H4K20me1_gene_body_N2.III, H4K20me1_gene_body_N2.notIII, alternative = "greater")
wilcox.IVvs.N2 <- wilcox.test(H4K20me1_gene_body_N2.IV, H4K20me1_gene_body_N2.notIV, alternative = "greater")
wilcox.Vvs.N2 <- wilcox.test(H4K20me1_gene_body_N2.V, H4K20me1_gene_body_N2.notV, alternative = "greater")

pvalue.Xvs.N2 <- wilcox.Xvs.N2$p.value
pvalue.Ivs.N2 <- wilcox.Ivs.N2$p.value
pvalue.IIvs.N2 <- wilcox.IIvs.N2$p.value
pvalue.IIIvs.N2 <- wilcox.IIIvs.N2$p.value
pvalue.IVvs.N2 <- wilcox.IVvs.N2$p.value
pvalue.Vvs.N2 <- wilcox.Vvs.N2$p.value

```

```{r}

## VARIABLES ##
all_vs.N2 = c(pvalue.Ivs.N2, pvalue.IIvs.N2, pvalue.IIIvs.N2, pvalue.IVvs.N2, pvalue.Vvs.N2, pvalue.Xvs.N2)
chromosomes = c("I", "II", "III", "IV", "V", "X")
##

pvals.vs.N2 <- all_vs.N2

pvalues.vs.N2 <- (data.frame(pvals = pvals.vs.N2))
pvalues.vs.N2$neglog10 <- -log10(pvalues.vs.N2$pvals) 


pvalues.vs.N2$chromosome <- chromosomes

```

***P. pacificus***

```{r}

## VARIABLES ##
chrI = "chrI"
chrII = "chrII"
chrIII = "chrIII"
chrIV = "chrIV"
chrV = "chrV"
chrX = "chrX"
##

H4K20me1_gene_body_PS312.I <- H4K20me1_gene_body_PS312$zscore[H4K20me1_gene_body_PS312$chromosome == chrI]
H4K20me1_gene_body_PS312.II <- H4K20me1_gene_body_PS312$zscore[H4K20me1_gene_body_PS312$chromosome == chrII]
H4K20me1_gene_body_PS312.III <- H4K20me1_gene_body_PS312$zscore[H4K20me1_gene_body_PS312$chromosome == chrIII]
H4K20me1_gene_body_PS312.IV <- H4K20me1_gene_body_PS312$zscore[H4K20me1_gene_body_PS312$chromosome == chrIV]
H4K20me1_gene_body_PS312.V <- H4K20me1_gene_body_PS312$zscore[H4K20me1_gene_body_PS312$chromosome == chrV]
H4K20me1_gene_body_PS312.X <- H4K20me1_gene_body_PS312$zscore[H4K20me1_gene_body_PS312$chromosome == chrX]

# these are sanity checks. compare with your summary statistics
mean(H4K20me1_gene_body_PS312.I, na.rm = TRUE)
mean(H4K20me1_gene_body_PS312.II, na.rm = TRUE)
mean(H4K20me1_gene_body_PS312.III, na.rm = TRUE)
mean(H4K20me1_gene_body_PS312.IV, na.rm = TRUE)
mean(H4K20me1_gene_body_PS312.V, na.rm = TRUE)
mean(H4K20me1_gene_body_PS312.X, na.rm = TRUE)

length(H4K20me1_gene_body_PS312.I)
length(H4K20me1_gene_body_PS312.II)
length(H4K20me1_gene_body_PS312.III)
length(H4K20me1_gene_body_PS312.IV)
length(H4K20me1_gene_body_PS312.V)
length(H4K20me1_gene_body_PS312.X)

```

```{r}

## VARIABLES ##
autosomes <- c(chrI, chrII, chrIII, chrIV)
notI <- c(chrII, chrIII, chrIV, chrX)
notII <- c(chrI, chrIII, chrIV, chrX)
notIII <- c(chrI, chrII, chrIV, chrX)
notIV <- c(chrI, chrII, chrIII, chrX)
notV <- c(chrI, chrII, chrIII, chrIV, chrX)

# subset
H4K20me1_gene_body_PS312.A <- H4K20me1_gene_body_PS312$zscore[H4K20me1_gene_body_PS312$chromosome %in% autosomes]
H4K20me1_gene_body_PS312.notI <- H4K20me1_gene_body_PS312$zscore[H4K20me1_gene_body_PS312$chromosome %in% notI]
H4K20me1_gene_body_PS312.notII <- H4K20me1_gene_body_PS312$zscore[H4K20me1_gene_body_PS312$chromosome %in% notII]
H4K20me1_gene_body_PS312.notIII <- H4K20me1_gene_body_PS312$zscore[H4K20me1_gene_body_PS312$chromosome %in% notIII]
H4K20me1_gene_body_PS312.notIV <- H4K20me1_gene_body_PS312$zscore[H4K20me1_gene_body_PS312$chromosome %in% notIV]
H4K20me1_gene_body_PS312.notV <- H4K20me1_gene_body_PS312$zscore[H4K20me1_gene_body_PS312$chromosome %in% notV]

# sanity check
mean(H4K20me1_gene_body_PS312.A, na.rm = TRUE)
mean(H4K20me1_gene_body_PS312.notI, na.rm = TRUE)
mean(H4K20me1_gene_body_PS312.notII, na.rm = TRUE)
mean(H4K20me1_gene_body_PS312.notIII, na.rm = TRUE)
mean(H4K20me1_gene_body_PS312.notIV, na.rm = TRUE)
mean(H4K20me1_gene_body_PS312.notV, na.rm = TRUE)

length(H4K20me1_gene_body_PS312.A)
length(H4K20me1_gene_body_PS312.notI)
length(H4K20me1_gene_body_PS312.notII)
length(H4K20me1_gene_body_PS312.notIII)
length(H4K20me1_gene_body_PS312.notIV)
length(H4K20me1_gene_body_PS312.notV)

```

```{r}

wilcox.Xvs.PS312 <- wilcox.test(H4K20me1_gene_body_PS312.X, H4K20me1_gene_body_PS312.A, alternative = "greater")
wilcox.Ivs.PS312 <- wilcox.test(H4K20me1_gene_body_PS312.I, H4K20me1_gene_body_PS312.notI, alternative = "greater")
wilcox.IIvs.PS312 <- wilcox.test(H4K20me1_gene_body_PS312.II, H4K20me1_gene_body_PS312.notII, alternative = "greater")
wilcox.IIIvs.PS312 <- wilcox.test(H4K20me1_gene_body_PS312.III, H4K20me1_gene_body_PS312.notIII, alternative = "greater")
wilcox.IVvs.PS312 <- wilcox.test(H4K20me1_gene_body_PS312.IV, H4K20me1_gene_body_PS312.notIV, alternative = "greater")
wilcox.Vvs.PS312 <- wilcox.test(H4K20me1_gene_body_PS312.V, H4K20me1_gene_body_PS312.notV, alternative = "greater")

pvalue.Xvs.PS312 <- wilcox.Xvs.PS312$p.value
pvalue.Ivs.PS312 <- wilcox.Ivs.PS312$p.value
pvalue.IIvs.PS312 <- wilcox.IIvs.PS312$p.value
pvalue.IIIvs.PS312 <- wilcox.IIIvs.PS312$p.value
pvalue.IVvs.PS312 <- wilcox.IVvs.PS312$p.value
pvalue.Vvs.PS312 <- wilcox.Vvs.PS312$p.value

```

```{r}

## VARIABLES ##
all_vs.PS312 = c(pvalue.Ivs.PS312, pvalue.IIvs.PS312, pvalue.IIIvs.PS312, pvalue.IVvs.PS312, pvalue.Vvs.PS312, pvalue.Xvs.PS312)
chromosomes = c("I", "II", "III", "IV", "V", "X")
##

pvals.vs.PS312 <- all_vs.PS312

pvalues.vs.PS312 <- (data.frame(pvals = pvals.vs.PS312))
pvalues.vs.PS312$neglog10 <- -log10(pvalues.vs.PS312$pvals) 


pvalues.vs.PS312$chromosome <- chromosomes

```

***O. tipulae***

```{r}

## VARIABLES ##
chrI = "I"
chrII = "II"
chrIII = "III"
chrIV = "IV"
chrV = "V"
chrX = "X"
##

H4K20me1_gene_body_CEW1.I <- H4K20me1_gene_body_CEW1$zscore[H4K20me1_gene_body_CEW1$chromosome == chrI]
H4K20me1_gene_body_CEW1.II <- H4K20me1_gene_body_CEW1$zscore[H4K20me1_gene_body_CEW1$chromosome == chrII]
H4K20me1_gene_body_CEW1.III <- H4K20me1_gene_body_CEW1$zscore[H4K20me1_gene_body_CEW1$chromosome == chrIII]
H4K20me1_gene_body_CEW1.IV <- H4K20me1_gene_body_CEW1$zscore[H4K20me1_gene_body_CEW1$chromosome == chrIV]
H4K20me1_gene_body_CEW1.V <- H4K20me1_gene_body_CEW1$zscore[H4K20me1_gene_body_CEW1$chromosome == chrV]
H4K20me1_gene_body_CEW1.X <- H4K20me1_gene_body_CEW1$zscore[H4K20me1_gene_body_CEW1$chromosome == chrX]

# these are sanity checks. compare with your summary statistics
mean(H4K20me1_gene_body_CEW1.I, na.rm = TRUE)
mean(H4K20me1_gene_body_CEW1.II, na.rm = TRUE)
mean(H4K20me1_gene_body_CEW1.III, na.rm = TRUE)
mean(H4K20me1_gene_body_CEW1.IV, na.rm = TRUE)
mean(H4K20me1_gene_body_CEW1.V, na.rm = TRUE)
mean(H4K20me1_gene_body_CEW1.X, na.rm = TRUE)

length(H4K20me1_gene_body_CEW1.I)
length(H4K20me1_gene_body_CEW1.II)
length(H4K20me1_gene_body_CEW1.III)
length(H4K20me1_gene_body_CEW1.IV)
length(H4K20me1_gene_body_CEW1.V)
length(H4K20me1_gene_body_CEW1.X)

```

```{r}

## VARIABLES ##
autosomes <- c(chrI, chrII, chrIII, chrIV)
notI <- c(chrII, chrIII, chrIV, chrX)
notII <- c(chrI, chrIII, chrIV, chrX)
notIII <- c(chrI, chrII, chrIV, chrX)
notIV <- c(chrI, chrII, chrIII, chrX)
notV <- c(chrI, chrII, chrIII, chrIV, chrX)

# subset
H4K20me1_gene_body_CEW1.A <- H4K20me1_gene_body_CEW1$zscore[H4K20me1_gene_body_CEW1$chromosome %in% autosomes]
H4K20me1_gene_body_CEW1.notI <- H4K20me1_gene_body_CEW1$zscore[H4K20me1_gene_body_CEW1$chromosome %in% notI]
H4K20me1_gene_body_CEW1.notII <- H4K20me1_gene_body_CEW1$zscore[H4K20me1_gene_body_CEW1$chromosome %in% notII]
H4K20me1_gene_body_CEW1.notIII <- H4K20me1_gene_body_CEW1$zscore[H4K20me1_gene_body_CEW1$chromosome %in% notIII]
H4K20me1_gene_body_CEW1.notIV <- H4K20me1_gene_body_CEW1$zscore[H4K20me1_gene_body_CEW1$chromosome %in% notIV]
H4K20me1_gene_body_CEW1.notV <- H4K20me1_gene_body_CEW1$zscore[H4K20me1_gene_body_CEW1$chromosome %in% notV]

# sanity check
mean(H4K20me1_gene_body_CEW1.A, na.rm = TRUE)
mean(H4K20me1_gene_body_CEW1.notI, na.rm = TRUE)
mean(H4K20me1_gene_body_CEW1.notII, na.rm = TRUE)
mean(H4K20me1_gene_body_CEW1.notIII, na.rm = TRUE)
mean(H4K20me1_gene_body_CEW1.notIV, na.rm = TRUE)
mean(H4K20me1_gene_body_CEW1.notV, na.rm = TRUE)

length(H4K20me1_gene_body_CEW1.A)
length(H4K20me1_gene_body_CEW1.notI)
length(H4K20me1_gene_body_CEW1.notII)
length(H4K20me1_gene_body_CEW1.notIII)
length(H4K20me1_gene_body_CEW1.notIV)
length(H4K20me1_gene_body_CEW1.notV)

```

```{r}

wilcox.Xvs.CEW1 <- wilcox.test(H4K20me1_gene_body_CEW1.X, H4K20me1_gene_body_CEW1.A, alternative = "greater")
wilcox.Ivs.CEW1 <- wilcox.test(H4K20me1_gene_body_CEW1.I, H4K20me1_gene_body_CEW1.notI, alternative = "greater")
wilcox.IIvs.CEW1 <- wilcox.test(H4K20me1_gene_body_CEW1.II, H4K20me1_gene_body_CEW1.notII, alternative = "greater")
wilcox.IIIvs.CEW1 <- wilcox.test(H4K20me1_gene_body_CEW1.III, H4K20me1_gene_body_CEW1.notIII, alternative = "greater")
wilcox.IVvs.CEW1 <- wilcox.test(H4K20me1_gene_body_CEW1.IV, H4K20me1_gene_body_CEW1.notIV, alternative = "greater")
wilcox.Vvs.CEW1 <- wilcox.test(H4K20me1_gene_body_CEW1.V, H4K20me1_gene_body_CEW1.notV, alternative = "greater")

pvalue.Xvs.CEW1 <- wilcox.Xvs.CEW1$p.value
pvalue.Ivs.CEW1 <- wilcox.Ivs.CEW1$p.value
pvalue.IIvs.CEW1 <- wilcox.IIvs.CEW1$p.value
pvalue.IIIvs.CEW1 <- wilcox.IIIvs.CEW1$p.value
pvalue.IVvs.CEW1 <- wilcox.IVvs.CEW1$p.value
pvalue.Vvs.CEW1 <- wilcox.Vvs.CEW1$p.value

```

```{r}

## VARIABLES ##
all_vs.CEW1 = c(pvalue.Ivs.CEW1, pvalue.IIvs.CEW1, pvalue.IIIvs.CEW1, pvalue.IVvs.CEW1, pvalue.Vvs.CEW1, pvalue.Xvs.CEW1)
chromosomes = c("I", "II", "III", "IV", "V", "X")
##

pvals.vs.CEW1 <- all_vs.CEW1

pvalues.vs.CEW1 <- (data.frame(pvals = pvals.vs.CEW1))
pvalues.vs.CEW1$neglog10 <- -log10(pvalues.vs.CEW1$pvals) 


pvalues.vs.CEW1$chromosome <- chromosomes

```

```{r}

pvalues.vs <- rbind(pvalues.vs.PS312, pvalues.vs.N2,pvalues.vs.CEW1)

pvalues.vs$species <- c(rep("P. pacificus", 6), rep("C. elegans", 6), rep("O. tipulae", 6))

```

Plot -log10(p-value) by chromosome. 
```{r}

custom_colors_2 <- c("#DDDDDD", "#BBBBBB", "#999999", "#777777", "#555555", "#D55E00")

pvalues.vs$species <- factor(pvalues.vs$species, levels = unique(pvalues.vs$species))

library(ggplot2)

p1 <- ggplot(pvalues.vs, aes(x = factor(species), y = neglog10, color = factor(chromosome)))

p1 + 
  geom_jitter(position = position_dodge(width = 0.4), 
              size = 2) +
  labs(x = "Species", 
       y = "-log10(p-value)", 
       color = "chromosome") +
  scale_color_manual(values = custom_colors_2,
                     breaks = c("I", "II", "III", "IV", "V", "X"),
                     labels = c("I", "II", "III", "IV", "V", "X")) +
  ylim(-20, 200) +
  geom_vline(xintercept = c(1.5, 2.5, 3.5,4.5, 5.5, 6.5), 
             linetype = "dashed", 
             color = "black", 
             size = 0.5) +
  theme_classic() +
  theme(axis.text.x = element_blank(),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        legend.text = element_text(size=8),
        legend.title = element_text(size=10))

file.name = "pvals-vs_chip_zcore_jitter.pdf"
ggsave(filename = file.name, dpi = 300, device = "pdf", width = 6, height = 2, units = "in")

```